
package br.com.infox.telas;

import br.com.infox.dal.ModuloConexao;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author thay
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    Connection conexao = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lbl_data = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menu_cadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_os = new javax.swing.JMenuItem();
        menu_usuarios = new javax.swing.JMenuItem();
        menu_relatorio = new javax.swing.JMenu();
        menu_rel_clientes = new javax.swing.JMenuItem();
        menu_rel_os = new javax.swing.JMenuItem();
        menu_ajuda = new javax.swing.JMenu();
        menu_sobre = new javax.swing.JMenuItem();
        menu_opcoes = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para controle de ordem de serviço");
        setPreferredSize(new java.awt.Dimension(915, 592));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(600, 510));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        lbl_data.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lbl_data.setText("Data");

        lbl_usuario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_usuario.setText("Usuario");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/icon_pc.png"))); // NOI18N

        menu_cadastro.setText("Cadastro");

        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_cadastro.add(jMenuItem1);

        menu_os.setText("Ordem Serviço");
        menu_os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_osActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_os);

        menu_usuarios.setText("Usuarios");
        menu_usuarios.setEnabled(false);
        menu_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_usuariosActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_usuarios);

        menu.add(menu_cadastro);

        menu_relatorio.setText("Relatorio");
        menu_relatorio.setEnabled(false);

        menu_rel_clientes.setText("Clientes");
        menu_rel_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rel_clientesActionPerformed(evt);
            }
        });
        menu_relatorio.add(menu_rel_clientes);

        menu_rel_os.setText("Ordem Serviço");
        menu_relatorio.add(menu_rel_os);

        menu.add(menu_relatorio);

        menu_ajuda.setText("Ajuda");

        menu_sobre.setText("Sobre");
        menu_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sobreActionPerformed(evt);
            }
        });
        menu_ajuda.add(menu_sobre);

        menu.add(menu_ajuda);

        menu_opcoes.setText("Opções");

        menu_sair.setText("Sair");
        menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sairActionPerformed(evt);
            }
        });
        menu_opcoes.add(menu_sair);

        menu.add(menu_opcoes);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_usuario)
                    .addComponent(lbl_data)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_usuario)
                        .addGap(31, 31, 31)
                        .addComponent(lbl_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sairActionPerformed
        // parasair 
        int sair = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair?","ATENÇAO",JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0);
        } 
    }//GEN-LAST:event_menu_sairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // mostrar a data na hora que tela principal for aberta
        Date data =  new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lbl_data.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menu_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sobreActionPerformed
        // chamando a tela sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_menu_sobreActionPerformed

    private void menu_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_usuariosActionPerformed
        // abrir a tela usuario dentro da area do desktop
        TelaUsuario tela_usuario = new TelaUsuario();
        tela_usuario.setVisible(true);
        desktop.add(tela_usuario);
    }//GEN-LAST:event_menu_usuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Chamando a tela de cliente
        TelaCliente tela_cliente = new TelaCliente();
        tela_cliente.setVisible(true);
        desktop.add(tela_cliente);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_osActionPerformed
       TelaOS tela_os = new TelaOS();
       tela_os.setVisible(true);
       desktop.add(tela_os);
    }//GEN-LAST:event_menu_osActionPerformed

    private void menu_rel_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rel_clientesActionPerformed
        //Gerando o relatorio de clientes
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja gera o relatorio de todos os clientes?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            // imprimindo o relatorio com framework JasperReports
            try{
                // Usando a classe JasperPrint para preaprar a impressao de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/Users/thay/Documents/NetBeansProjects/projeto-infox1/reports/clientes.jasper",null,conexao);
                // exibindo o relatorio pela classe JasperViewer
                JasperViewer.viewReport(print,false);
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_menu_rel_clientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl_data;
    public static javax.swing.JLabel lbl_usuario;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_ajuda;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenu menu_opcoes;
    private javax.swing.JMenuItem menu_os;
    private javax.swing.JMenuItem menu_rel_clientes;
    private javax.swing.JMenuItem menu_rel_os;
    public static javax.swing.JMenu menu_relatorio;
    private javax.swing.JMenuItem menu_sair;
    private javax.swing.JMenuItem menu_sobre;
    public static javax.swing.JMenuItem menu_usuarios;
    // End of variables declaration//GEN-END:variables
}
